### PR TITLE
Issue 57: copy previous month's location

### PR DESCRIPTION
**Pull request by BrianEnigma**

### CODE REVIEW

**Comment by civrot** [comment]
@BrianEnigma Are you looking for a review for this one, or is it still in progress?

**Comment by BrianEnigma** [comment]
As far as I know, this is ready to go...?

**Comment by civrot** [comment]
Sorry, for taking so long to reply.  Can you add a test for the new copy action? Otherwise this is awesome!

**Comment by BrianEnigma** [comment]
To test the copy and recent_locations functions, I think I either need to populate the database with known data or I need a mock to fake the same. I can't seem to find where in the rspec chain of hidden magic that's supposed to occur.

**Comment by BrianEnigma** [comment]
This should be good to go, yes?

**Comment by civrot** [comment]
Yeah...except there are broken specs @BrianEnigma

**Pull request merged**
